[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "https://luxm-salon-agra.vercel.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
